name: mobidev_hasura
description: Easy handling of hasura's features. Like Query, Mutations and Upsert (mutation).
version: 0.1.2
repository: https://github.com/DiegoDionisio/mobidev_hasura/

environment:
  sdk: ^3.1.0

dependencies:
  dio: ^5.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
